/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bet;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jirka
 */
public class Bet extends javax.swing.JFrame {

    int random;
    Double initial;
    Double ratio;
    Double bet;
    int number;
    double record;
    String name;
    String recordHolder;

    /**
     * Creates new form Bet
     */
    public Bet() {
        initComponents();
        setSize(822, 630);

        setLocationRelativeTo(null);

    }

    public Bet(String para) {
        initComponents();
        setSize(822, 630);
        setLocationRelativeTo(null);

        jName.setText(para);

        jtxtPoints.setText(String.valueOf(1000));

        ArrayList<String> seznam = new ArrayList<String>();
        String line;
        double record;

        try (BufferedReader reader = new BufferedReader(new FileReader("D:\\Betting_game\\record.txt"))) {
            line = reader.readLine();
            while (line != null) {
                seznam.add(line);
                line = reader.readLine();
            }
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        record = Double.parseDouble(seznam.get(seznam.size() - 2));
        recordHolder = seznam.get(seznam.size() - 1);

        jtxtRecord.setText(String.valueOf(record));
        jtxtRecordHolder.setText(recordHolder);

    }

    public static boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (Exception e) {
            return false;
        }

    }

    public static boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtPoints = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtBet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jtxtResult = new javax.swing.JTextField();
        jtxtRecord = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtxtRecordHolder = new javax.swing.JTextField();
        jName = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        PossibleWin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setToolTipText("Game");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Betting Game");

        jtxtPoints.setEditable(false);
        jtxtPoints.setBackground(new java.awt.Color(255, 255, 255));
        jtxtPoints.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPoints.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPointsActionPerformed(evt);
            }
        });
        jtxtPoints.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPointsKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Your points:");

        jtxtBet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtBet.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBetActionPerformed(evt);
            }
        });
        jtxtBet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBetKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Your bet:");

        jtxtNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberActionPerformed(evt);
            }
        });
        jtxtNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNumberKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Your number:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtxtResult.setEditable(false);
        jtxtResult.setBackground(new java.awt.Color(255, 255, 255));
        jtxtResult.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jtxtResult.setToolTipText("");
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });

        jtxtRecord.setEditable(false);
        jtxtRecord.setBackground(new java.awt.Color(255, 255, 255));
        jtxtRecord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtRecord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRecordActionPerformed(evt);
            }
        });
        jtxtRecord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtRecordKeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("START");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Record");

        jtxtRecordHolder.setEditable(false);
        jtxtRecordHolder.setBackground(new java.awt.Color(255, 255, 255));
        jtxtRecordHolder.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtRecordHolder.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtRecordHolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtRecordHolderActionPerformed(evt);
            }
        });

        jName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setText("RULES");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        PossibleWin.setEditable(false);
        PossibleWin.setBackground(new java.awt.Color(255, 255, 255));
        PossibleWin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PossibleWin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PossibleWinMouseEntered(evt);
            }
        });
        PossibleWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PossibleWinActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Possible win:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jtxtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(PossibleWin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(554, 554, 554)
                                .addComponent(jtxtRecordHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jtxtBet, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtxtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(252, 252, 252)
                                                .addComponent(jtxtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(341, 341, 341)
                                        .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtBet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PossibleWin, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtRecordHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        File file = new File("D:\\Betting_game\\record.txt");
        file.setWritable(true);
     
               
        
        
        
        boolean hasnotenough = (Double.parseDouble(jtxtBet.getText()) > Double.parseDouble(jtxtPoints.getText()));
        boolean outofbounds = (Integer.parseInt(jtxtNumber.getText()) > 99 || Integer.parseInt(jtxtNumber.getText()) < 0);
        boolean notinteger = (isInteger(jtxtNumber.getText()) == false || isDouble(jtxtBet.getText()) == false);

        if (hasnotenough == true || outofbounds == true || notinteger == true) {
            JOptionPane.showMessageDialog(null, "You did not enter right information", "Error message", JOptionPane.ERROR_MESSAGE);
            jtxtBet.setText(null);
            jtxtNumber.setText(null);
        } else {
            Random rnd = new Random();

            random = rnd.nextInt(100) + 1;
            jtxtResult.setText(String.valueOf(random));
            initial = Double.parseDouble(jtxtPoints.getText());
            ratio = 100 / (Double.parseDouble(jtxtNumber.getText()));
            bet = Double.parseDouble(jtxtBet.getText());
            number = Integer.parseInt(jtxtNumber.getText());

            if (Double.parseDouble(jtxtNumber.getText()) > Double.parseDouble(jtxtResult.getText())) {
                initial += (ratio - 1) * bet;
                initial = (double) Math.round(100 * initial) / 100;
                JOptionPane.showMessageDialog(null, "You win! Your number " + number + " is bigger than " + random + "." + " You have won " + (ratio - 1) * bet + ".", "Winning message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                initial -= bet;
                initial = (double) Math.round(100 * initial) / 100;
                JOptionPane.showMessageDialog(null, "You lost! Your number " + number + " is smaller than " + random + "." + " You have lost " + bet + ".", "Losing message", JOptionPane.INFORMATION_MESSAGE);
            }

            jtxtBet.setText(null);
            jtxtNumber.setText(null);
            jtxtPoints.setText(String.valueOf(initial));

            if (initial == 0) {
                JOptionPane.showMessageDialog(null, "You have lost all your money", "THE END", JOptionPane.INFORMATION_MESSAGE);
                jtxtPoints.setText(String.valueOf(1000));
            }

            // finding out the record
            ArrayList<String> seznam2 = new ArrayList<String>();
            String line;
            double record;

            try (BufferedReader reader = new BufferedReader(new FileReader("D:\\Betting_game\\record.txt"))) {
                line = reader.readLine();
                while (line != null) {
                    seznam2.add(line);
                    line = reader.readLine();

                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            record = Double.parseDouble(seznam2.get(seznam2.size() - 2));

            if (initial > record) {
                String text = String.valueOf(initial);
                String text2 = jName.getText();
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("D:\\Betting_game\\record.txt", true))) {
                    writer.newLine();
                    writer.write(text);
                    writer.newLine();
                    writer.write(text2);
                    writer.newLine();
                } catch (IOException e) {
                    System.out.println(e.getMessage());
                }

                jtxtRecord.setText(String.valueOf(initial));

                jtxtRecordHolder.setText(jName.getText());
                
                 file.setReadOnly();

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberActionPerformed

    private void jtxtBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBetActionPerformed

    private void jtxtPointsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPointsKeyPressed
        JOptionPane.showMessageDialog(null, "You tried to cheat, and you will be punished!", "CHEATER!", JOptionPane.ERROR_MESSAGE);
        jtxtPoints.setText(String.valueOf(0));
    }//GEN-LAST:event_jtxtPointsKeyPressed

    private void jtxtPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPointsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPointsActionPerformed

    private void jtxtRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRecordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        if (! new File("D:\\Betting_game").isFile()) {
            try {
                File dir = new File("D:\\Betting_game");
                dir.mkdir();
                
                Process p = Runtime.getRuntime().exec("attrib +h " + dir.getPath());
                try {
                    p.waitFor();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Bet.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(Bet.class.getName()).log(Level.SEVERE, null, ex);
            }
               
        }
        
        
        if (! new File("D:\\Betting_game\\record.txt").isFile()) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("D:\\Betting_game\\record.txt", true))) {
                writer.write("0");
                writer.newLine();
                writer.write("unkown");
                writer.newLine();
                
                File file = new File("D:\\Betting_game\\record.txt");
                file.setReadOnly();
                
                 Process p = Runtime.getRuntime().exec("attrib +h " + file.getPath());
                try {
                    p.waitFor();
                } catch (InterruptedException ex) {
                    Logger.getLogger(Bet.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            } catch (IOException e) {
                System.out.println(e.getMessage());
            }

        } else {

        }

        Player p = new Player();
        p.setVisible(true);

        dispose();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtxtRecordHolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtRecordHolderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRecordHolderActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Rules r = new Rules();
        r.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PossibleWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PossibleWinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PossibleWinActionPerformed

    private void jtxtBetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBetKeyTyped


    }//GEN-LAST:event_jtxtBetKeyTyped

    private void jtxtNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNumberKeyTyped


    }//GEN-LAST:event_jtxtNumberKeyTyped

    private void PossibleWinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PossibleWinMouseEntered
        try {
            ratio = 100 / (Double.parseDouble(jtxtNumber.getText()));
            bet = Double.parseDouble(jtxtBet.getText());

            double d = bet * (ratio - 1);
            double dd = Math.round(100 * d) / 100;
            String s = String.valueOf(d);

            PossibleWin.setText(String.format("%.2f", d));
        } catch (Exception e) {
            PossibleWin.setText("");
        }    }//GEN-LAST:event_PossibleWinMouseEntered

    private void jtxtRecordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtRecordKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtRecordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PossibleWin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtBet;
    private javax.swing.JTextField jtxtNumber;
    private javax.swing.JTextField jtxtPoints;
    private javax.swing.JTextField jtxtRecord;
    private javax.swing.JTextField jtxtRecordHolder;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
